# Create your Kivy layout in the kv language here
BoxLayout:
    orientation: "horizontal"

    BoxLayout:
        size_hint_x: 0.2
        orientation: "vertical"

        Label:
            text: "Sort by:"
        Spinner:
            id: sort_spinner
            text: 'Name'
            values: ['Name', 'Country', 'Priority', 'is_visited']

        Label:
            text: 'Add new Place'
        Label:
            text: 'Name'
        TextInput:
            id: name_input

        Label:
            text: 'Country'
        TextInput:
            id: country_input

        Label:
            text: 'Priority'
        TextInput:
            id: priority_input

        Button:
            text: 'Add Place'
            # on_press: app.add_new_place()
        Button:
            text: 'Clear'
            # on_press: app.clear_all()

    BoxLayout:
        size_hint_x: 0.8
        orientation: "vertical"

        BoxLayout:
            size_hint_y: 0.8
            orientation: "vertical"

            Label:
                # text: app.display_number_of_unvisited()
                text: "Number of unvisited places: 0"  # Example static text

        BoxLayout:
            Button:
                id: welcome_message
                text: "Welcome to Travel Tracker 2.0"