# Create your Kivy layout in the kv language here
BoxLayout:
    orientation:"horizontal"
    BoxLayout:
        size_hint_x: 0.2
        orientation: "vertical"
        Label:
        Spinner:
        Label:
        Label:
        TextInput:
        Label:
        TextInput:
        Label:
        TextInput:
        Button:
        Button:
    BoxLayout:
        size_hint_x: 0.8
        orientation: "vertical"
        BoxLayout:
            size_hint_y: 0.8
            orientation:"vertical"
        BoxLayout:
            Button:



